version: '3.8'

services:
  app:
    build: .
    environment:
      APP_NAME: "Laravel Counter"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "https://app-laravel-counter.azurewebsites.net"
      APP_KEY: base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4=
      
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: "${DB_PASSWORD}"
      
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: