name: 'Laravel Azure Deployment'
description: 'Deploy Laravel application to Azure Web App'

on:
  workflow_call:
    secrets:
      AZURE_APP_NAME:
        description: 'Name of the Azure Web App'
        required: true
      AZURE_PUBLISH_PROFILE:
        description: 'Azure Web App publish profile'
        required: true
      AZURE_CREDENTIALS:
        description: 'Azure credentials JSON'
        required: true
      APP_KEY:
        description: 'Laravel application key'
        required: true
      DB_PASSWORD:
        description: 'Database password'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug secrets
        run: |
          if [ -n "${{ secrets.AZURE_APP_NAME }}" ]; then
            echo "AZURE_APP_NAME est défini"
          else
            echo "AZURE_APP_NAME n'est pas défini"
          fi
          if [ -n "${{ secrets.AZURE_PUBLISH_PROFILE }}" ]; then
            echo "AZURE_PUBLISH_PROFILE est défini"
          else
            echo "AZURE_PUBLISH_PROFILE n'est pas défini"
          fi
          if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS est défini"
          else
            echo "AZURE_CREDENTIALS n'est pas défini"
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug AZURE_CREDENTIALS
        run: |
          echo "Vérification du format JSON de AZURE_CREDENTIALS:"
          echo '${{ secrets.AZURE_CREDENTIALS }}' | jq '.'
          
          echo "Vérification des permissions du Service Principal:"
          CLIENTID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')
          echo "Client ID: $CLIENTID"
          az role assignment list --assignee "$CLIENTID" --output json | jq '.'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, bcmath, soap, zip
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Fix permissions for Laravel storage & bootstrap
        run: |
          chmod -R 777 storage bootstrap/cache
          mkdir -p storage/framework/{sessions,views,cache}

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Vérifier les fichiers avant déploiement
        run: |
          echo "=== Contenu du répertoire racine ==="
          ls -la
          echo "=== Contenu du répertoire public ==="
          ls -la public
          echo "=== Contenu du répertoire storage ==="
          ls -la storage
          echo "=== Contenu du répertoire bootstrap/cache ==="
          ls -la bootstrap/cache

      - name: Configure MySQL Firewall
        run: |
          # Get the public IP of the GitHub Actions runner
          PUBLIC_IP=$(curl -s https://api.ipify.org)
          echo "GitHub Actions IP: $PUBLIC_IP"

          # Create a temporary firewall rule
          az mysql flexible-server firewall-rule create \
            --name githubactions_temp \
            --resource-group rg-laravel-counter-app \
            --server-name laravelmysqlsrv \
            --start-ip-address $PUBLIC_IP \
            --end-ip-address $PUBLIC_IP

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/*" "node_modules/*" "vendor/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip

      - name: Verify Deployment
        run: |
          echo "🔍 Vérification du déploiement..."
          echo "📂 URL de l'application: https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net"
          echo "📂 URL Kudu (SCM): https://${{ secrets.AZURE_APP_NAME }}.scm.azurewebsites.net"
          
          # Attendre que l'application soit disponible
          sleep 30
          
          # Vérifier si l'application répond
          curl -I "https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net"

      - name: Remove MySQL Firewall Rule
        if: always()
        run: |
          az mysql flexible-server firewall-rule delete \
            --name githubactions_temp \
            --resource-group rg-laravel-counter-app \
            --server-name laravelmysqlsrv \
            --yes 