name: Deploy to Azure
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, fileinfo, gd
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Create SSL directory and copy certificate
        run: |
          sudo mkdir -p /etc/ssl/certs
          sudo cp certs/DigiCertGlobalRootCA.crt.pem /etc/ssl/certs/Baltimore_CyberTrust_Root.crt.pem
          sudo chmod 644 /etc/ssl/certs/Baltimore_CyberTrust_Root.crt.pem

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=https://laravel-counter-app.azurewebsites.net" >> .env
          
          # MySQL Configuration
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=laravelmysqlsrv.mysql.database.azure.com" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laraveldb" >> .env
          echo "DB_USERNAME=mysqladmin@laravelmysqlsrv" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MYSQL_SSL=true" >> .env
          echo "MYSQL_ATTR_SSL_CA=/etc/ssl/certs/Baltimore_CyberTrust_Root.crt.pem" >> .env
          
          # Azure Storage Configuration
          echo "FILESYSTEM_DRIVER=azure" >> .env
          echo "AZURE_STORAGE_NAME=laravelcounterfiles" >> .env
          echo "AZURE_STORAGE_KEY=${{ secrets.AZURE_STORAGE_KEY }}" >> .env
          echo "AZURE_STORAGE_CONTAINER=uploads" >> .env
          echo "AZURE_STORAGE_URL=https://laravelcounterfiles.blob.core.windows.net" >> .env

      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
          mkdir -p storage/framework/{sessions,views,cache}

      - name: Generate Application Key
        run: php artisan key:generate --force

      - name: Prepare deployment package
        run: |
          rm -rf .git .github .env.example
          cp .env .env.backup
          zip -r release.zip .
          cp .env.backup .env

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'laravel-counter-app'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip

      - name: Post-deployment setup
        run: |
          # Attendre que le déploiement soit effectif
          sleep 30
          
          # Vérifier le déploiement
          curl -I https://laravel-counter-app.azurewebsites.net 